### PR TITLE
Add changes necessary to generate popolo for our councillor data

### PR DESCRIPTION
**Pull request by equivalentideas**
The [upstream csv_to_popolo](https://github.com/tmtmtmtm/csv_to_popolo) works for people who are members of a federal legislature, but not local councillors. These changes adapt it for use with Australian local councillor data so it can be used to generate the data for https://github.com/openaustralia/australian_local_councillors_popolo .

### CODE REVIEW

**Comment by henare** [comment]
D'oh! These changes were already [on a branch](https://github.com/openaustralia/csv_to_popolo/tree/australian_local_councillors), which is what [australian_local_councillors_popolo](https://github.com/openaustralia/australian_local_councillors_popolo/pull/6/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R4) is configured to use on the pull request we're working on. It was my intention that we keep master in sync with upstream, like we do for other gems in this situation.

**Comment by equivalentideas** [comment]
> D'oh! These changes were already on a branch, which is what australian_local_councillors_popolo is configured to use on the pull request we're working on. It was my intention that we keep master in sync with upstream, like we do for other gems in this situation.

Nice, that makes sense. Would you like to revert this merge @henare ?

**Comment by henare** [comment]
Reverting will make master even more different to upstream. It doesn't materially matter but we should probably nuke master and start from upstream if we want to do what I was suggesting above.

**Comment by equivalentideas** [comment]
> Reverting will make master even more different to upstream. It doesn't materially matter but we should probably nuke master and start from upstream if we want to do what I was suggesting above.

I'm gonna do this nuke and restart now so we don't forget about it.

**Comment by equivalentideas** [comment]
> I'm gonna do this nuke and restart now so we don't forget about it.

Done, master is back at upstream master.

**Pull request merged**
